apiVersion: v1
kind: Service
metadata:
    name: ptmjyothishpythonsamplevscodeflasktutorial
spec:
    type: LoadBalancer
    ports:
    - port: 5000 
    selector:
        app: ptmjyothishpythonsamplevscodeflasktutorial